### ISSUE TITLE
COMP230 Pre-production Tasks and Pitches - clarification on term "game middleware"

### ISSUE THREAD

**Issue by NecroReindeer** [Falmouth-Games-Academy/bsc-assignment-briefs#10]
One of the options for working on the assignment states:

> work in any conﬁguration (including individual) to develop a game-making tool or game middleware that another BA/BSc team could make use of

For the purposes of this assignment, what type of thing is meant by "game middleware"?

**Comment by Adrir** [comment]
> **Middleware** is a piece of software that is integrated into a larger software system to handle some specialized aspect it. **Game middleware** is designed specifically to integrate into game engines, handling aspects of games such as their physics, graphics or networking.
> [https://en.wikipedia.org/wiki/List_of_game_middleware](https://en.wikipedia.org/wiki/List_of_game_middleware)
