### ISSUE TITLE
COMP230 Pre-production Tasks and Pitches - "Use of Version Control" criterion query

### ISSUE THREAD

**Issue by NecroReindeer** [Falmouth-Games-Academy/bsc-assignment-briefs#9]
Regarding the "Use of Version Control" criterion on COMP230's "Pre-production Tasks and Pitches" assignment:
One of the requirements states

> There is extensive evidence of engagement with peers (e.g. code review).

This is easy to achieve in a group as you can review each others' code and send pull requests to each other. What are students who choose to work individually expected to do in order to fulfill this requirement?

**Comment by Adrir** [comment]
We anticipate that BSc students will support each other and review each others' code irrespective of their team memberships or working contexts.
